/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EntrepreneurProfile {
  'id' : bigint,
  'contact' : string,
  'businessName' : string,
  'description' : string,
  'creatorPrincipal' : Principal,
  'category' : ProductCategory,
}
export interface ProductCategory {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface ProductInquiry {
  'id' : bigint,
  'customerName' : string,
  'customerContact' : string,
  'productId' : bigint,
  'entrepreneurId' : bigint,
  'message' : string,
}
export interface ProductListing {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'entrepreneurId' : bigint,
  'creatorPrincipal' : Principal,
  'category' : ProductCategory,
  'price' : bigint,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProduct' : ActorMethod<
    [bigint, string, string, bigint, bigint],
    ProductListing
  >,
  'createOrUpdateProfile' : ActorMethod<
    [string, string, bigint, string],
    EntrepreneurProfile
  >,
  'createProductInquiry' : ActorMethod<
    [bigint, bigint, string, string, string],
    ProductInquiry
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<ProductCategory>>,
  'getInquiriesByEntrepreneur' : ActorMethod<[bigint], Array<ProductInquiry>>,
  'getProduct' : ActorMethod<[bigint], ProductListing>,
  'getProductsByCategory' : ActorMethod<[bigint], Array<ProductListing>>,
  'getProductsByEntrepreneur' : ActorMethod<[bigint], Array<ProductListing>>,
  'getProfile' : ActorMethod<[bigint], EntrepreneurProfile>,
  'getProfilesByCategory' : ActorMethod<[bigint], Array<EntrepreneurProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeMarketplace' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];