/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ProductListing = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'entrepreneurId' : IDL.Nat,
  'creatorPrincipal' : IDL.Principal,
  'category' : ProductCategory,
  'price' : IDL.Nat,
});
export const EntrepreneurProfile = IDL.Record({
  'id' : IDL.Nat,
  'contact' : IDL.Text,
  'businessName' : IDL.Text,
  'description' : IDL.Text,
  'creatorPrincipal' : IDL.Principal,
  'category' : ProductCategory,
});
export const ProductInquiry = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'customerContact' : IDL.Text,
  'productId' : IDL.Nat,
  'entrepreneurId' : IDL.Nat,
  'message' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [ProductListing],
      [],
    ),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [EntrepreneurProfile],
      [],
    ),
  'createProductInquiry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [ProductInquiry],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(ProductCategory)], ['query']),
  'getInquiriesByEntrepreneur' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProductInquiry)],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [ProductListing], ['query']),
  'getProductsByCategory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProductListing)],
      ['query'],
    ),
  'getProductsByEntrepreneur' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProductListing)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Nat], [EntrepreneurProfile], ['query']),
  'getProfilesByCategory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(EntrepreneurProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeMarketplace' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ProductListing = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'entrepreneurId' : IDL.Nat,
    'creatorPrincipal' : IDL.Principal,
    'category' : ProductCategory,
    'price' : IDL.Nat,
  });
  const EntrepreneurProfile = IDL.Record({
    'id' : IDL.Nat,
    'contact' : IDL.Text,
    'businessName' : IDL.Text,
    'description' : IDL.Text,
    'creatorPrincipal' : IDL.Principal,
    'category' : ProductCategory,
  });
  const ProductInquiry = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'customerContact' : IDL.Text,
    'productId' : IDL.Nat,
    'entrepreneurId' : IDL.Nat,
    'message' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [ProductListing],
        [],
      ),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [EntrepreneurProfile],
        [],
      ),
    'createProductInquiry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [ProductInquiry],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(ProductCategory)], ['query']),
    'getInquiriesByEntrepreneur' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProductInquiry)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [ProductListing], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProductListing)],
        ['query'],
      ),
    'getProductsByEntrepreneur' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProductListing)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Nat], [EntrepreneurProfile], ['query']),
    'getProfilesByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(EntrepreneurProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeMarketplace' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };